### ISSUE TITLE
Missing fs-extra dependency

### ISSUE THREAD

**Issue by peritpatrio** [dfrankland/hyperterm-tab-icons#1]
Could not successfully build without installing fs-extra.

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXXXX/.hyperterm_plugins/local/hyperterm-tab-icons/tools/build.js:4:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by dfrankland** [comment]
Thanks for catching this! Fixed here https://github.com/dfrankland/hyperterm-tab-icons/commit/07682828ffa499da72e39f533fcdbbc3005fda25
