### ISSUE TITLE
Error: title.split is not a function

### ISSUE THREAD

**Issue by BenDiuguid** [dfrankland/hyperterm-tab-icons#5]
Hey I am receiving this error and am unable to do anything.

I have the following plugins installed:

```
plugins: [
    'hyperterm-tab-icons',
    'hyperpower',
    'hypercwd',
    'hyperterm-tabs',
  ],
```

```
bundle.js:1 TypeError: title.split is not a function
    at getIcon (/Users/odinson/.hyperterm_plugins/node_modules/hyperterm-tab-icons/index.js:45:41)
    at getCustomTitle (/Users/odinson/.hyperterm_plugins/node_modules/hyperterm-tab-icons/index.js:51:16)
    at exports.getTabsProps (/Users/odinson/.hyperterm_plugins/node_modules/hyperterm-tab-icons/index.js:83:25)
    at file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:1:5903
    at Array.forEach (native)
    at getTabsProps (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:1:5837)
    at Header.value (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:5:24939)
    at Header.value (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:1:22483)
    at _renderValidatedComponentWithoutOwnerOrContext (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:15:26851)
    at _renderValidatedComponent (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:15:26939)
```

I'm guessing there is some incompatability with `hyperterm-tab-icons` and `hyperterm-tabs`.

Let me know if you  need any other information! I'm happy to help if possible!

**Comment by dfrankland** [comment]
Hmmm, seems to only be happening when there's 1 tab open... Shouldn't be too difficult to fix 👍

**Comment by BenDiuguid** [comment]
Awesome! Let me know if you need anything!

**Comment by dfrankland** [comment]
Should be fixed with this commit: https://github.com/dfrankland/hyperterm-tab-icons/commit/ffd1dc5acadffd7c8b7b03a8c74b1b9de97548fb

Update to version 1.0.3 for the fix and let me know if it works! 🎱

**Comment by BenDiuguid** [comment]
Awesome works with `hyperterm-tabs` as expected! 👍
